In [21]:
import torch
import numpy as np

# Create a tensor filled with zeros (4 rows and 5 columns)
zero_tensor = torch.zeros(4, 5)  

# Create a tensor filled with ones (4 rows and 5 columns)
one_tensor = torch.ones(4, 5)

# Create a tensor with random numbers uniformly distributed between 0 and 1 (4 rows and 6 columns)
rand_tensor = torch.rand(4, 6)

# Define data as nested lists (2 rows, 3 columns)
data = [[1, 2, 3], [111, 43, 6]]

# Create a 2D tensor from the existing Python data
x = torch.tensor(data)

# Uncomment to inspect the created tensors:
# print(zero_tensor)
# print(one_tensor)
# print(rand_tensor)
print(x)

tensor([[  1,   2,   3],
        [111,  43,   6]])


In [22]:
# Inspect the dimensions / shape of the tensor:
# - x.shape: attribute (standard in NumPy and PyTorch)
# - x.size(): PyTorch method
# Both return torch.Size([2, 3]) indicating 2 rows and 3 columns
print(x.size())
print(x.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [23]:
# Common Tensor Attributes

# Create a random tensor of shape (3, 5)
tensor = torch.rand(3, 5)

# Print the tensor values
print("Tensor values:\n", tensor)

# 1. Dimensions / Shape of the tensor:
print("\nSize (method):", tensor.size())   # returns torch.Size([3, 5])
print("Shape (attribute):", tensor.shape)  # returns torch.Size([3, 5])

# 2. Data type of elements (default is torch.float32 for float tensors):
print("Data type:", tensor.dtype)

# 3. Hardware device where tensor is stored ('cpu' or 'cuda'/'mps'):
print("Device:", tensor.device)

In [27]:
# Operations on Tensors: Indexing, Slicing & Mutation

# 1. Device check: Check for available hardware accelerator (GPU/MPS/etc.)
if torch.accelerator.is_available():
    device = torch.accelerator.current_accelerator()
    print(f"Using accelerator: {device}")
else:
    device = "cpu"
    print("Using CPU")

# 2. Create a 3x3 tensor filled with 1s
tensor = torch.ones(3, 3, device=device)
print("\nInitial Tensor (3x3 ones):\n", tensor)

# 3. NumPy-like Indexing and Slicing:
# Access the first row (index 0)
print("\nFirst row (tensor[0]):\n", tensor[0])

# Access the last column (index 2 across all rows)
print("\nLast column (tensor[:, 2]):\n", tensor[:, 2])

# 4. In-place Value Modifications:
# Set the entire 3rd row (index 2) to 0
tensor[2] = 0
print("\nAfter setting row 2 to 0 (tensor[2] = 0):\n", tensor)

# Set the 2nd row (slice 1:2) to 33
tensor[1:2] = 33
print("\nAfter setting row slice 1:2 to 33 (tensor[1:2] = 33):\n", tensor)

Using accelerator: cuda

Initial Tensor (3x3 ones):
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

First row (tensor[0]):
 tensor([1., 1., 1.], device='cuda:0')

Last column (tensor[:, 2]):
 tensor([1., 1., 1.], device='cuda:0')

After setting row 2 to 0 (tensor[2] = 0):
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]], device='cuda:0')

After setting row slice 1:2 to 33 (tensor[1:2] = 33):
 tensor([[ 1.,  1.,  1.],
        [33., 33., 33.],
        [ 0.,  0.,  0.]], device='cuda:0')
