In [2]:
import torch
import numpy as np

# Create a tensor filled with zeros (4 rows and 5 columns)
zero_tensor = torch.zeros(4, 5)  

# Create a tensor filled with ones (4 rows and 5 columns)
one_tensor = torch.ones(4, 5)

# Create a tensor with random numbers uniformly distributed between 0 and 1 (4 rows and 6 columns)
rand_tensor = torch.rand(4, 6)

# Define data as nested lists (2 rows, 3 columns)
data = [[1, 2, 3], [111, 43, 6]]

# Create a 2D tensor from the existing Python data
x = torch.tensor(data)

# Uncomment to inspect the created tensors:
# print(zero_tensor)
# print(one_tensor)
# print(rand_tensor)
print(x)

tensor([[  1,   2,   3],
        [111,  43,   6]])


In [3]:
# Inspect the dimensions / shape of the tensor:
# - x.shape: attribute (standard in NumPy and PyTorch)
# - x.size(): PyTorch method
# Both return torch.Size([2, 3]) indicating 2 rows and 3 columns
print(x.size())
print(x.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [4]:
# Common Tensor Attributes

# Create a random tensor of shape (3, 5)
tensor = torch.rand(3, 5)

# Print the tensor values
print("Tensor values:\n", tensor)

# 1. Dimensions / Shape of the tensor:
print("\nSize (method):", tensor.size())   # returns torch.Size([3, 5])
print("Shape (attribute):", tensor.shape)  # returns torch.Size([3, 5])

# 2. Data type of elements (default is torch.float32 for float tensors):
print("Data type:", tensor.dtype)

# 3. Hardware device where tensor is stored ('cpu' or 'cuda'/'mps'):
print("Device:", tensor.device)

Tensor values:
 tensor([[0.9933, 0.4487, 0.9427, 0.0360, 0.6188],
        [0.7117, 0.0645, 0.1419, 0.4907, 0.0619],
        [0.3217, 0.6314, 0.8625, 0.3649, 0.6048]])

Size (method): torch.Size([3, 5])
Shape (attribute): torch.Size([3, 5])
Data type: torch.float32
Device: cpu


In [5]:
# Operations on Tensors: Indexing, Slicing & Mutation

# 1. Device check: Check for available hardware accelerator (GPU/MPS/etc.)
if torch.accelerator.is_available():
    device = torch.accelerator.current_accelerator()
    print(f"Using accelerator: {device}")
else:
    device = "cpu"
    print("Using CPU")

# 2. Create a 3x3 tensor filled with 1s
tensor = torch.ones(3, 3, device=device)
print("\nInitial Tensor (3x3 ones):\n", tensor)

# 3. NumPy-like Indexing and Slicing:
# Access the first row (index 0)
print("\nFirst row (tensor[0]):\n", tensor[0])

# Access the last column (index 2 across all rows)
print("\nLast column (tensor[:, 2]):\n", tensor[:, 2])

# 4. In-place Value Modifications:
# Set the entire 3rd row (index 2) to 0
tensor[2] = 0
print("\nAfter setting row 2 to 0 (tensor[2] = 0):\n", tensor)

# Set the 2nd row (slice 1:2) to 33
tensor[1:2] = 33
print("\nAfter setting row slice 1:2 to 33 (tensor[1:2] = 33):\n", tensor)

Using accelerator: cuda

Initial Tensor (3x3 ones):
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

First row (tensor[0]):
 tensor([1., 1., 1.], device='cuda:0')

Last column (tensor[:, 2]):
 tensor([1., 1., 1.], device='cuda:0')

After setting row 2 to 0 (tensor[2] = 0):
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]], device='cuda:0')

After setting row slice 1:2 to 33 (tensor[1:2] = 33):
 tensor([[ 1.,  1.,  1.],
        [33., 33., 33.],
        [ 0.,  0.,  0.]], device='cuda:0')


In [6]:
# Joining / Concatenating Tensors

# In PyTorch, use `dim` (not `ndim`) to specify the concatenation dimension:
# - dim=0: concatenate vertically (along rows)
# - dim=1: concatenate horizontally (along columns)

# Concatenating along columns (dim=1)
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print("Concatenated along columns (dim=1):\n", t1)
print("Shape of t1:", t1.shape)

Concatenated along columns (dim=1):
 tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [33., 33., 33., 33., 33., 33., 33., 33., 33.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], device='cuda:0')
Shape of t1: torch.Size([3, 9])


In [7]:
# ==========================================
# Arithmetic Operations in PyTorch
# ==========================================

# 1. MATRIX MULTIPLICATION (Linear algebra product)
# Note: `tensor.T` returns the transpose of a tensor.
# y1, y2, y3 will compute the exact same matrix multiplication result:

# Option A: Python '@' operator (most common & concise)
y1 = tensor @ tensor.T

# Option B: Tensor method .matmul()
y2 = tensor.matmul(tensor.T)

# Option C: torch.matmul function with pre-allocated `out=` tensor
y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

print("--- Matrix Multiplication (tensor @ tensor.T) ---")
print("y1:\n", y1)
print("Do y1, y2, y3 have identical values?", torch.equal(y1, y2) and torch.equal(y1, y3))


# 2. ELEMENT-WISE MULTIPLICATION (Hadamard product)
# Multiplies elements at matching positions (a_ij * b_ij).
# z1, z2, z3 will compute the exact same element-wise product:

# Option A: Standard '*' operator
z1 = tensor * tensor

# Option B: Tensor method .mul()
z2 = tensor.mul(tensor)

# Option C: torch.mul function with pre-allocated `out=` tensor
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print("\n--- Element-wise Multiplication (tensor * tensor) ---")
print("z1:\n", z1)
print("Do z1, z2, z3 have identical values?", torch.equal(z1, z2) and torch.equal(z1, z3))

--- Matrix Multiplication (tensor @ tensor.T) ---
y1:
 tensor([[3.0000e+00, 9.9000e+01, 0.0000e+00],
        [9.9000e+01, 3.2670e+03, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]], device='cuda:0')
Do y1, y2, y3 have identical values? True

--- Element-wise Multiplication (tensor * tensor) ---
z1:
 tensor([[1.0000e+00, 1.0000e+00, 1.0000e+00],
        [1.0890e+03, 1.0890e+03, 1.0890e+03],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]], device='cuda:0')
Do z1, z2, z3 have identical values? True


In [11]:
# one element tensor  / aggregate function

agg= tensor.sum()
agg_items = agg.item()
print(agg_items , type(agg_items))


102.0 <class 'float'>


In [13]:
# in place operation

print(tensor)
tensor.add_(10)
print(tensor)

tensor([[ 1.,  1.,  1.],
        [33., 33., 33.],
        [ 0.,  0.,  0.]], device='cuda:0')
tensor([[11., 11., 11.],
        [43., 43., 43.],
        [10., 10., 10.]], device='cuda:0')


In [14]:
# tensor to numpy

t =  torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
# a change in tensor can also change the numpy
t  = t.add_(10)
print(t)
print(n)

tensor([11., 11., 11., 11., 11.])
[11. 11. 11. 11. 11.]
